### ISSUE TITLE
En la classe xxxxJPAManager el metode create es genera amb synchronized

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/genapp#100]
En la classe xxxxJPAManager el metode create es genera amb synchronized. Com que això ja ho gestiona la BBDD lllavors es pot llevar.

**Comment by ptrias-fundaciobit** [comment]
Solucionat: 
![image](https://user-images.githubusercontent.com/95921330/167369296-6a59c155-baf8-4d3c-90d4-743ee3861cf9.png)
