### ISSUE TITLE
Afegir codi java per consultar informació de l'usuari loguejat a traves del Plugin de User Information

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/genapp#101]
Afegir codi java per consultar informació de l'usuari loguejat a traves del PLugin de User Information. Es pot utilitzar com exemple github.com/Fundacio-Bit/enviafib:
   (1) Revisar Canvi de pom.xml de ear
   (2) Revisar classe enviafib/enviafib-back/src/main/java/es/caib/enviafib/back/security/AuthenticationSuccessListener.java

Les dades de l'usuari recuperat es guardaran dins de LoginInfo dins una mateixa estructura retornada per l'API de UserInformation (crec que es UserInfo)

**Comment by fbosch-fundaciobit** [comment]
S'ha introduit el plugin de UserInformation:

![image](https://user-images.githubusercontent.com/40387703/171375029-4d05fa02-c43c-4908-b077-bc0d8abf19bc.png)
