### ISSUE TITLE
Eliminar el SCHEMA public quan es crea el fitxer genapp per primera vegada

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/genapp#104]
Eliminar el SCHEMA public quan es crea el fitxer genapp per primera vegada.
Quan es crea el .sql i el .genapp inicial, aquest darrer es crea amb un schema "public". El schema no s'ha de definir cosa que far+à que genapp mostri a l'usuari quin SCHEMA DE BBDD utilitzar.

**Comment by ptrias-fundaciobit** [comment]
Solucionat, ara surt el desplegable d'opcions per elegir l'esquema a l'hora d'Actualitzar projecte (canvis BBDD)
