### ISSUE TITLE
Afegir classe d'utilitat per gestionar enviament de correus dins de EJB.

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/genapp#105]
Afegir classe d'utilitat per gestionar enviament de correus dins de EJB.

En la versió GenApp 1.0 hi havia una classe d'utilittat per enviar correus directament i enviar correus a traves d'una coa. 

Mirar si es poden fer funcionar per JBOSS 7.2 o com a mínim  enviar correus directament.

**Comment by ptrias-fundaciobit** [comment]
Ara està la classe EmailUtil, a logic/utils, amb el mètode postMail(), que passant els paràmetres corresponents, envia un email:
![image](https://user-images.githubusercontent.com/95921330/180748096-8dea7057-da9d-48f2-8a90-cd69a5291b4a.png)
![image](https://user-images.githubusercontent.com/95921330/180748640-5973ac69-93f5-4df9-aa41-9d56f43e2b0d.png)

**Comment by ptrias-fundaciobit** [comment]
Queda pendent el tema de enviar correus a traves d'una coa
