### ISSUE TITLE
Canviar directori de files.directory de system.properties

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/genapp#108]
La propietat files.directory del ftxer de xxx.system.properties del codi plantilla de disn genapp-gen val "/tmp/...".
(1) Aquest directori  confon i no pot ser /tmp ja que aquest és temporal (s'esborra cada vegada que reinicies el servidor). Gràcies.
(2) A més posar un exemple de directori en windows comentat
D:/[[projectname]]/files

**Comment by fbosch-fundaciobit** [comment]
S'ha canviat la ruta per defecte, i s'ha inclos un comentari amb l'exemple de la ruta:

![image](https://user-images.githubusercontent.com/40387703/170490634-3fda7a25-e267-414e-a3a0-231ed5f4b313.png)

**Comment by anadal-fundaciobit** [comment]
No s'ha fet el que es demanava:
(1) Es demanava posar un directori tipus linux però que no fos /tmp
(2) L'exemple NO pot ser ni un directori temporal ni un directori relatiu
(3) Es demanava que l'exemple COMENTAT  fos en WINDOWS

**Comment by fbosch-fundaciobit** [comment]
![image](https://user-images.githubusercontent.com/40387703/170680613-71d6ca8b-659c-4fbd-88aa-d447a671c88b.png)
