### ISSUE TITLE
Substituir jar de taglibs-unstandard.jar per dependència maven

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/genapp#110]
Substituir jar de taglibs-unstandard.jar per dependència maven:

1. Eliminar jar de  [project]-back\src\main\webapp\WEB-INF\lib
2. Al pom.xml del back de genapp afegir la següent dependència
```
<dependency>
    <groupId>taglibs</groupId>
    <artifactId>taglibs-unstandard</artifactId>
    <version>20060829</version>
</dependency>
```

**Comment by fbosch-fundaciobit** [comment]
S'ha eliminat taglibs-unstandard.jar i s'ha afegit la dependència amb les funcionalitats.

![image](https://user-images.githubusercontent.com/40387703/170458633-c83ba1c3-c182-4e5a-baa4-a128cb9fa2ec.png)
