### ISSUE TITLE
Error no controlat quan no s'ha definit la propietat files.directory

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/genapp#32]
Error no controlat quan no s'ha definit la propietat files.directory. Revisar el Configuracio de commons  per veure si allà es pot comprovar:
   (1) Si les propietats del standalone estan definides
   (2)  Si les propietats del standalone apunten a fitxers
   (3)  L'existència de la propietat XXX.files.directory
   (4) Que la propietat   XXX.files.directory apunti a un directori amb permisos d'escriptura

**Comment by anadal-fundaciobit** [comment]
(1) Els dos primers missatges ...


```
No existeix la propietat 'filesdirectory' al fitxer 'system.properties'.\n"
        			+ "S'hauria d'anar al fitxer '.system.properties' de JBoss standalone/deployments i incloure la propietat 'filesdirectory' amb una ruta al directori on l'aplició gestionara els fitxers.
					
No s'ha definit la propietat 'filesdirectory' al fitxer 'system.properties'.\n"
        			+ "S'hauria d'anar al fitxer '.system.properties' de JBoss standalone/deployments i donar valor a la propietat 'filesdirectory' amb una ruta al directori on l'aplició gestionara els fitxers."
```

es poden substituir per				
					
					
`No existeix o no s'ha definit la propietat '[FALTA_PACKAGE].filesdirectory' al document " + getFileSystemPropertiesPath()[IMPLEMENTAR-HO] + ". Aquesta propietat hauria d`incloure una ruta a un directori on l'APLICACIÓ GUARDARÀ els fitxers.`

(2) No posar else's ja que hi ha THROWS
(3) En els missatges no posar "\n"

**Comment by fbosch-fundaciobit** [comment]
S'ha afegit el control de que el fitxer tingui permisos d'escriptura.

![image](https://user-images.githubusercontent.com/40387703/169474347-fd5c59ba-f87c-417c-96c5-8340957e681d.png)
