### ISSUE TITLE
Es genera de forma incorrecta el compile.bat i compile.sh 

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/genapp#56]
En el compile conté la següent comanda (similar en linux):

`xcopy /Y genappsqltutorialear\target\genappsqltutorial.ear %GENAPPSQLTUTORIAL_DEPLOY_DIR%`

però no funciona ja que el direcori de 'ear' necessita un guió (-):

`xcopy /Y genappsqltutorial-ear\target\genappsqltutorial.ear %GENAPPSQLTUTORIAL_DEPLOY_DIR%`

Arreglar el generador.

**Comment by ptrias-fundaciobit** [comment]
Solucionat. Ara ja es crea amb el guió:

compile.bat:
	  xcopy /Y instanciagenerica-ear\target\instanciagenerica.ear %INSTANCIAGENERICA_DEPLOY_DIR%

compile.sh
	  cp ./instanciagenerica-ear/target/instanciagenerica.ear $INSTANCIAGENERICA_DEPLOY_DIR
