### ISSUE TITLE
Boto de tancar en la vista de "Agrupació" dels llistats

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/genapp#76]
Devora de l'etiqueta "Agrupar per ... " hi ha un boto que per alguna raó no es visialitza i serveix per desactivar/ocultar el filtre per Agrupació. Veure que està passant. 

![imagen](https://user-images.githubusercontent.com/17084256/141773093-189ed552-3c68-45dd-afdf-6596b0495000.png)

**Comment by ptrias-fundaciobit** [comment]
No solucionat. Generant demogenapp surt correcte:
![image](https://user-images.githubusercontent.com/95921330/181003169-f257e49f-01d2-4d94-b805-222c6f953e00.png)
