### ISSUE TITLE
Llista desplegable d'accions no es mostra correctament.

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/genapp#77]
Pareix que les llistes deplegables no es mostren correctament al no poder sortir del div en el que es troben: Veure captura 1 i 2.

En la versió antiga, veure captura 3, aquest problema no existia.  Pareix que Bootstrap ha canvia la forma de fer-ho: https://getbootstrap.com/docs/4.0/components/dropdowns/

![imagen](https://user-images.githubusercontent.com/17084256/141773478-4d45af26-ba01-43e4-b1fa-a6efabb5e596.png)

![imagen](https://user-images.githubusercontent.com/17084256/141773500-626645a8-2f69-4a9e-b26f-fa5dcb98dad0.png)

![imagen](https://user-images.githubusercontent.com/17084256/141774430-91f5a05d-ae10-409e-b650-65d73fd2de47.png)

**Comment by ptrias-fundaciobit** [comment]
No apareix cap error de visualització:
![image](https://user-images.githubusercontent.com/95921330/166673544-60f808ea-44df-48f2-bc70-7b02856bda33.png)
