### ISSUE TITLE
No funciona Amagar menú

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/genapp#79]
Cada menú inclou un boto en la part dreta superior que serveix per amagar el menu. El menu desapareix però l'espai que ocupara resta. El problema és que s'oculta el menú però l'espai que ocupava no es buida. Veure captura 1 i 2

Una posible solució seria modificar les classes css assignades a cada columna (Veure captura 3):
           * Columna 1[MENU]: Mostrar => col-3   | Amagar Menu => ""
           * Columna 2[CONTINGUT]: Mostrar => col-9  | Amagar menu => col-11

![imagen](https://user-images.githubusercontent.com/17084256/141780357-49d00c9c-bde7-49a2-a0dd-ac9dd25eed37.png)

![imagen](https://user-images.githubusercontent.com/17084256/141780379-d160ee86-2a99-4b3d-aa4c-44ab36053118.png)

![imagen](https://user-images.githubusercontent.com/17084256/141780871-773e2e11-b030-42cf-9d77-4ca2175109d7.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat: pasa de col-3 i col-9 a res i col-12 (col-11 no queda be)
![image](https://user-images.githubusercontent.com/95921330/180175502-1f69d119-d740-492b-af7f-e2818927d0a5.png)
![image](https://user-images.githubusercontent.com/95921330/180175472-1eeba955-0058-498b-bce5-00cbabb691be.png)

**Comment by ptrias-fundaciobit** [comment]
S'ha modificat a portafib, no a genapp!

**Comment by ptrias-fundaciobit** [comment]
Ara si està a GenApp (provat a DEMO)
![image](https://user-images.githubusercontent.com/95921330/180184680-5831f814-fb63-4a1a-8dd0-464cc7b9d3f4.png)
![image](https://user-images.githubusercontent.com/95921330/180184645-5f1c4c4c-e090-415b-ab12-cc574b7c4513.png)
