### ISSUE TITLE
Millores en com usar i manual d'usuari

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/genapp#80]
* Millores en com usar: EL Readme.md explica les primeres passes emprant GenApp. Estan antiquades i falta un punt d'afegir repository als settings.xml

* Manual d'usuari: El manual d'usuari és de la versió 1.0. S'ha d'actualitzar a la versió 2.0

**Comment by anadal-fundaciobit** [comment]
https://github.com/GovernIB/maven/commit/f96f2c237d0b121a89caf5c9df4b011404bdc9ef

**Comment by ptrias-fundaciobit** [comment]
Solucionat. Afegit manual per desenvolupar
