### ISSUE TITLE
Millorar  canvi idioma al BACK 

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/genapp#89]
Millorar  canvi idioma al BACK . Fer-ho com està fet a Instancia generica: https://github.com/Fundacio-Bit/instanciagenerica/blob/instanciagenerica-1.0/instanciagenerica-back/src/main/webapp/WEB-INF/jsp/moduls/cap.jsp

**Comment by ptrias-fundaciobit** [comment]
Solucionat
