### ISSUE TITLE
Poder afegir seccions a Formulari de GenApp

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/genapp#90]
Poder agrupar els camps d'un formulari GenApp en seccions tal i com s'ha aconseguit dins de Instància Generica: 

(1) Revisar codi per fer seccions d'aqui:  https://github.com/Fundacio-Bit/instanciagenerica/blob/instanciagenerica-1.0/instanciagenerica-back/src/main/webapp/WEB-INF/jsp/webdbmodificable/instanciaGenericaFormModificable.jsp.
(2) Crear dins GenApp una estructura de dades JAVA  que serveixi per construir la variable javascript seccions. (genapp-web -> form)
(3) Incloure l'estructura de dades anterior a BaseForm (org.fundaciobit.genapp.common.web.form.BaseForm)
(4) Replicar codi COMU necessari per generar seccions  dins d'un JSP de GenApp .
(5) Inclore referència al jsp del punt (3) dins de XXXXForm.jsp

**Comment by ptrias-fundaciobit** [comment]
Solucionat
