### ISSUE TITLE
Apareixen warnings dins d'Eclipse en la generació neta d'un projecte

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/genapp#94]
Apareixen warnings dins d'Eclipse de "VARIABLE is never used" i de "IMPORT is never used".
Revisar la plantilla de genapp on apareixen codis d'aquests.

**Comment by ptrias-fundaciobit** [comment]
Solucionat. Tots els neverused de demogenapp están arreglats:
![image](https://user-images.githubusercontent.com/95921330/165278226-664402d7-6d5b-4eda-9422-18e612751018.png)
