### ISSUE TITLE
Afegir nom a l'anotació @Entity

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/genapp#95]
Afegir nom a l'anotació @Entity tal i com es veu a la primera captura. Les Entity creades actualment no duen "name" (veure captura 2)

![imagen](https://user-images.githubusercontent.com/17084256/164232451-376792ac-37e5-48a3-b893-3d4e2dd3bc3f.png)

![imagen](https://user-images.githubusercontent.com/17084256/164232659-c3e9d61f-887f-4253-8690-bdfd4a1eb93c.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat:

![image](https://user-images.githubusercontent.com/95921330/166920141-f8f2a9f4-5543-42df-b544-c492e5acc16b.png)

**Comment by anadal-fundaciobit** [comment]
Faltava  JPA en el nom de l'entitySolucionat.
