### ISSUE TITLE
Afegir codi per controlar que s'hagin definit propietats correctament

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/genapp#96]
Afegir codi per controlar que s'hagin definit propietats correctament

M'he adonat que el errors més frequents a l'hora de posar un servidor en marxa són dos:
  (1) Que les propietats definides dins de l'standalone (apunten al properties i system.properties) o s'obliden d'afegir-les, o les escriuen malament o la ruta on apunten no existeix.
  (2) S'obliden de definir la ruta correcte a un directori de fitxers definida dins del XXXX.system.properties (filesdirectory)

Per cada cas dels anterior que surti un error amb un missatge MOLT DESCRIPTIU del que està passant.

**Comment by ptrias-fundaciobit** [comment]
Arreglat, ara surten exceptions indicant l'error més clarament:
![image](https://user-images.githubusercontent.com/95921330/166913019-855f9c99-99b0-41ca-be69-7f4b1ae27385.png)

**Comment by ptrias-fundaciobit** [comment]
Solucionat: 
![image](https://user-images.githubusercontent.com/95921330/170452938-67813953-c9e0-4e12-b3f3-35fbd0c71e8c.png)
