### ISSUE TITLE
Clau Primaria de tipus Integer no funciona

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/genapp#98]
Provar d'assignar una clau primatia a un tipus int, regenerar codi i compilar. 

Dins es Controladors (back/controller/webdb/XXXXController.Java)
Sa funcio stringToPK dona error quan sa primery key es un Integer, es genapp genera es parse amb es nom de funcio equivocat.
Es genApp genera parseInteger pero sa funcio ha de ser parseInt

public java.lang.Integer stringToPK(String value) {
  return java.lang.Integer.parseInteger(value, 10);
}
public java.lang.Integer stringToPK(String value) {
  return java.lang.Integer.parseInt(value, 10);
}

**Comment by ptrias-fundaciobit** [comment]
Solucionat
