### ISSUE TITLE
Tipus BigDecimal no funciona correctament

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/genapp#99]
Si es defineix un camp de bbdd per a que sigui mapejat en GenApp emprant el tipus java.math.BigDecimal, internament es genera un cridada a una funció que no existeix. Arreglar-ho.
Revisar si a java.math.BigInteger li passa el mateix.

[ERROR] /C:/Desarrollo/Proyectos/huse_oracle_XE/huseback/src/main/java/org/fundaciobit/huse/back/controller/webdb/TipusDocumentController.java:[435,30] cannot find symbol
  symbol:   method parseBigDecimal(java.lang.String,int)
  location: class java.math.BigDecimal
[ERROR] /C:/Desarrollo/Proyectos/huse_oracle_XE/huseback/src/main/java/org/fundaciobit/huse/back/controller/webdb/ViaController.java:[488,30] cannot find symbol
  symbol:   method parseBigDecimal(java.lang.String,int)
  location: class java.math.BigDecimal
[ERROR] /C:/Desarrollo/Proyectos/huse_oracle_XE/huseback/src/main/java/org/fundaciobit/huse/back/controller/webdb/PersonaController.java:[435,30] cannot find symbol
  symbol:   method parseBigDecimal(java.lang.String,int)

**Comment by anadal-fundaciobit** [comment]
Si el Decimal descrit dins value és més gran que el que permet un Double fallarà. El que ha de retornar és new BigDecinal(value)

**Comment by ptrias-fundaciobit** [comment]
Ok, no sabia com fer-ho. SOLUCIONAT:
![image](https://user-images.githubusercontent.com/95921330/167408535-92c5715c-0633-4013-a667-8677f25aa110.png)
